language: python
python:
  - "2.6"
  - "2.7"
matrix:
  allow_failures:
    - python: "2.6"
install:
  - "pip install . --use-mirrors"
  - "pip install -r requirements_for_test.txt --use-mirrors"
script: nosetests
